# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95da3998579660d729dbe164f397fddbe16c760c6a9e1947180733069cc1e47103230a47df41c0556a0c7fddc1876ec3577f31eb12f69c930ef0ef2c7e45e784

test:
  secret_key_base: 7523602ae1c128259592c06ba09a1e623291d0945d014e66c1e79c147b09d4bac01c7aa6e336da6f4902a7b45d328d434d9ef17f8872bb89d60574db530b3594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
